### PR TITLE
Various fixes for event bus, rule, and rule target creations so that the project works correctly with localstack

### PR DESCRIPTION
**Pull request by shahmirn**
The individual commits have specific details. The gist is that the example project wasn't working and was blowing up when it was trying to create the rule and was also blowing up saying that the queue didn't exist.

After these changes, the typescript sample project works as expected, creating the event bus, the rules, the rule targets, and the queues.

### CODE REVIEW

**Comment by shahmirn** [comment]
@rubenkaiser could you take a look when you get a chance? Thanks!

**Comment by rubenkaiser** [comment]
@shahmirn I'm currently on a holiday but as soon as I get a chance I'll take a look. Thanks

**Comment by shahmirn** [comment]
Sounds good. Thanks!

**Comment by shahmirn** [comment]
@rubenkaiser Pinging again, in case this slipped through the cracks. Thanks!

**Comment by rubenkaiser** [comment]
@shahmirn Changes looked good. I've just released version 2.2.0. Thanks

**Pull request merged**
