### PR TITLE
feature/localstack support

### PR DESCRIPTION
**Pull request by MichalOleszczuk**
Hello.

This PR changes a lot of things so please bare with me.

Introduced features:
- TypeScript support
- Husky pre-commit and auto linter + formatting
- Localstack integration
- localstack example with typescript EventBridge -> SNS -> SQS -> Lambda
- All readmes and instructions are provided along with test
- package.json version has been updated

**IMPORTANT** We need to **modify publishing to npm** to perform npm run install -> npm run build in root. package.json already points to dist/src/index.js

### CODE REVIEW

**Review by rubenkaiser — COMMENTED** [review]
At first glance it looks good. I will test it in my local setup and release a beta version if that succeeds

**Comment by rubenkaiser** [comment]
You can check the workings by installing the beta release:
serverless-offline-aws-eventbridge@2.1.0-beta.0

**Comment by MichalOleszczuk** [comment]
@rubenkaiser - tested looking fine.

**Comment by JetUni** [comment]
Hey @MichalOleszczuk, I'm happy to see this got merged as well as my PR. Your comment above about testing this in your local setup makes me wonder if you have a list of tests that you run or something like that? I'd love to contribute more by adding unit tests to strengthen this project. And I have another update and I wanna make sure it doesn't break anything

**Comment by MichalOleszczuk** [comment]
@JetUni - not yet I am planning to implement tests in future. Starting with integration tests (docker serverless and checking of deployed in localstack resources with script at the end making request), they would give most value for implementation. 
Also in future (after I am bit more free) I want to provide integrations for SQS and lambda (resource definition)  as targets.

For now if you want to test just perform build and run typescript example with and without localstack configuration - both should work.

**Comment by JetUni** [comment]
I'm experiencing a problem with installing the package locally after this update. So, when I try to run serverless offline in my project after installing this package via `npm i ../serverless-offline-eventBridge`, then I get this error, but I have the same setup as before and it was working before this change

```
Serverless plugin "serverless-offline-aws-eventbridge" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file. Run "serverless plugin install -n serverless-offline-aws-eventbridge" to install it.
```

Current plugins:
``` yml
plugins:
  - serverless-deployment-bucket
  - '@company/private-plugin'
  - serverless-offline
  - serverless-offline-aws-eventbridge
  - serverless-plugin-log-subscription
  - serverless-plugin-split-stacks
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-plugin-ifelse
```

**Comment by MichalOleszczuk** [comment]
@JetUni  - strange can you check in your node_modules if it is present? 
This is my package.json
``` "serverless-offline-aws-eventbridge": "2.1.0-beta.0", ```
This is what I see in node_modules
node_modules
Those are my plugins
``` typescript
plugins: [
      'serverless-dotenv-plugin',
      'serverless-esbuild',
      'serverless-offline',
      'serverless-offline-sqs',
      'serverless-offline-sns',
      'serverless-offline-aws-eventbridge',
      'serverless-localstack',
    ]
```

And my custom
```typescript      
['serverless-offline-aws-eventbridge']: {
        localStackConfig: {
          localStackEndpoint: 'http://localhost:4566',
        },
      },
```

[Also example we have seems to work](https://github.com/rubenkaiser/serverless-offline-eventBridge/tree/master/examples/typescript/localstack/sns-sqs-lambda) 

Keep us posted when you discover what's wrong :D

**Comment by JetUni** [comment]
Yeah, it was just a pebcak error, forgetting to run the build command 🤦🏼‍♂️

**Pull request merged**
