### PR TITLE
fix: lambda calls for eventBridge

### PR DESCRIPTION
**Pull request by JamesKyburz**
Fix calling of lambdas using the same approach as [serverless-offline-dynamodb-streams](https://github.com/CoorpAcademy/serverless-plugins/tree/master/packages/serverless-offline-dynamodb-streams), it will now work for non javascript handlers too, also the environment variables along with IS_OFFLINE will now be correct.

I also removed the cron logic, this is because serverless-offline has built in support for eventBridge scheduled events.

### CODE REVIEW

**Comment by rubenkaiser** [comment]
Hi James, Good work on this. I just checked it in my test setup and there seems to be an issue combining this with serverless webpack (Error: SyntaxError: Cannot use import statement outside a module). Have you checked this? I may be doing something wrong since I did not have much time testing it yet.

Also serverless-offline should be listed as a peer dependency, otherwise an error is given for the dist folder in serverless-offline. Can you also remove the underscores from the functions so it is in line with the other code.

**Comment by JamesKyburz** [comment]
Would it be possible for you to send me your `webpack.config.js` so I can have a look?

**Comment by rubenkaiser** [comment]
In a small test project of mine I use the following setup:

```
service: serverlessOfflineEventbridgeTest

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-offline-aws-eventbridge

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    host: 0.0.0.0
  serverless-offline-aws-eventbridge:
    port: 4010
    debug: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
```

With the following webpack.config:
```
const slsw = require("serverless-webpack");
const nodeExternals = require("webpack-node-externals");

module.exports = {
  entry: slsw.lib.entries,
  target: "node",
  // Since 'aws-sdk' is not compatible with webpack,
  // we exclude all node dependencies
  externals: [nodeExternals()],
  mode: slsw.lib.webpack.isLocal ? "development" : "production",
  optimization: {
    // We no not want to minimize our code.
    minimize: false
  },
  performance: {
    // Turn off size warnings for entry points
    hints: false
  },
  // Run babel on all .js files and skip those in node_modules
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: "babel-loader",
        include: __dirname,
        exclude: /node_modules/
      }
    ]
  }
};
```

For the complete picture: here's the .babelrc
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "12"
        }
      }
    ]
  ],
  "plugins": [
    "@babel/plugin-transform-runtime"
  ]
}
```

**Comment by JamesKyburz** [comment]
Mmmm, I haven't managed to get the same result :(

I added all the webpack and babel changes to https://github.com/JamesKyburz/dynamodb-logs which uses my fork, and it worked with and without webpack.

**Comment by rubenkaiser** [comment]
In your javascript handler, for example, change the line in which you require DynamoDb to the ES6 import syntax:

```
import DynamoDB from "aws-sdk/clients/dynamodb";
```

**Comment by rubenkaiser** [comment]
I managed to fix it, check out https://github.com/rubenkaiser/serverless-offline-eventBridge/pull/17

You can get version 1.4.0 from npm to test it since I forgot to publish the package as a beta.

**Comment by JamesKyburz** [comment]
nice! interesting that I didn't run into issues even though I didn't either have serverless-offline as a peerDependency...

I can verify that https://github.com/JamesKyburz/dynamodb-logs works with the latest (1.4.0) release :)

**Comment by JamesKyburz** [comment]
Managed to recreate the syntax error by changing the import in my dynamodb handler, funny enough I had previously tested using esm imports in the eventbridge handler and that had worked....

Anyway I can verify the webpack error existed, and is now fixed in 1.4.0 :)

**Pull request merged**
