### PR TITLE
feat: retry lambda

### PR DESCRIPTION
**Pull request by JamesKyburz**
Add the ability to retry lambda functions, default is to retry 10 times waiting 500ms.

This doesn't try to mimic the behavior in AWS, but adds a simply retry with a configurable max.

PS. I didn't use [promise-retry](https://github.com/IndigoUnited/node-promise-retry) because of both out of date dependencies and that we don't need all the extra random ability that it provides.

### CODE REVIEW

**Comment by rubenkaiser** [comment]
Looks good. I will check it in more detail this week.

**Comment by JamesKyburz** [comment]
Let me know if you want me to make any changes.

**Comment by rubenkaiser** [comment]
I see you've made the amount of retries configurable. Think it would be nice to also do this with the waiting time between retries.

Apart from that I was also wondering if you have any ideas on the Promise.all and the map function in there (with the no-await-in-loop). 

This has been on my todo list since I don't really like the way we've implemented it now.

**Comment by JamesKyburz** [comment]
I have made the retry delay configurable too, also refactored the nested async map.

What do you think?

**Comment by JamesKyburz** [comment]
I tested it by adding the following to my handler :)

```js
if (Math.random() < 0.3) throw new Error("random failure");
```

**Comment by rubenkaiser** [comment]
Looks good. Really putting some effort in it, thanks. I don't have much time currently. I'll test it in my environment somewhere this week.

**Pull request merged**
